// $.ajaxSetup({
//     async: false,
// });

// $.get("edit.html").done((data) => {
//     html_main = data;
// });

// $.get("edit.html", function(result) {
//     html_main = result;
// })

// var xmlhttp = new XMLHttpRequest();
// xmlhttp.open("GET", 'edit.html', false);
// xmlhttp.send();
// html_main = xmlhttp.responseText;
// debugger;
// initialize with defaults
// HTML for Main Container //
var html_main = "";
html_main += "<div class=\"svd_container\">";
html_main += "	<ul class=\"navbar-default container-fluid nav nav-tabs svd_menu\">";
html_main += "		<li data-bind=\"css: {active: koViewType() == \'designer\'}\">";
html_main += "			<a data-bind=\"click:selectDesignerClick, text: $root.getLocString(\'ed.designer\')\" href=\"#\"><\/a>";
html_main += "		<\/li>";
html_main += "		<li data-bind=\"css: {active: koViewType() == \'editor\'}\">";
html_main += "			<a data-bind=\"click:selectEditorClick, text: $root.getLocString(\'ed.jsonEditor\')\" href=\"#\"><\/a>";
html_main += "		<\/li>";
html_main += "		<li data-bind=\"css: {active: koViewType() == \'test\'}\">";
html_main += "			<a data-bind=\"click:selectTestClick, text: $root.getLocString(\'ed.testSurvey\')\" href=\"#\"><\/a>";
html_main += "		<\/li>";
html_main += "		<li class=\"svd_actions\" data-bind=\"visible: koIsShowDesigner\"><button class=\"btn btn-primary\" data-bind=\"enable:undoRedo.koCanUndo, click: doUndoClick\" type=\"button\"><span data-bind=\"text: $root.getLocString(\'ed.undo\')\"><\/span><\/button><\/li>";
html_main += "		<li class=\"svd_actions\" data-bind=\"visible: koIsShowDesigner\"><button class=\"btn btn-primary\" data-bind=\"enable:undoRedo.koCanRedo, click: doRedoClick\" type=\"button\"><span data-bind=\"text: $root.getLocString(\'ed.redo\')\"><\/span><\/button><\/li>";
html_main += "		<li class=\"svd_actions\" data-bind=\"visible: koIsShowDesigner\">";
html_main += "			<div class=\"btn-group inline\" data-bind=\"visible: koShowOptions()\">";
// html_main += "				<button aria-expanded=\"false\" aria-haspopup=\"true\" class=\"btn btn-primary dropdown-toggle\" data-bind=\"text: $root.getLocString(\'ed.options\')\" data-toggle=\"dropdown\" type=\"button\">Options <span class=\"caret\"><\/span><\/button>";
html_main += "				<ul class=\"dropdown-menu\">";
html_main += "					<li data-bind=\"css: {active: koGenerateValidJSON}\">";
html_main += "						<a data-bind=\"click:generateValidJSONClick, text: $root.getLocString(\'ed.generateValidJSON\')\" href=\"#\"><\/a>";
html_main += "					<\/li>";
html_main += "					<li data-bind=\"css: {active: !koGenerateValidJSON()}\">";
html_main += "						<a data-bind=\"click:generateReadableJSONClick, text: $root.getLocString(\'ed.generateReadableJSON\')\" href=\"#\"><\/a>";
html_main += "					<\/li>";
html_main += "				<\/ul>";
html_main += "			<\/div>";
html_main += "		<\/li>";
html_main += "		<li class=\"svd_actions\" data-bind=\"visible: koViewType() == \'test\'\">";
html_main += "			<div class=\"btn-group inline\">";
html_main += "				<button aria-expanded=\"true\" aria-haspopup=\"true\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" id=\"surveyTestWidth\" type=\"button\"><span data-bind=\"text: $root.getLocString(\'ed.testSurveyWidth\') + \' \' + $root.koTestSurveyWidth()\"><\/span> <span class=\"caret\"><\/span><\/button>";
html_main += "				<ul aria-labelledby=\"surveyTestWidth\" class=\"dropdown-menu\">";
html_main += "					<li>";
html_main += "						<a data-bind=\"click: koTestSurveyWidth.bind($data, \'100%\')\" href=\"#\">100%<\/a>";
html_main += "					<\/li>";
html_main += "					<li>";
html_main += "						<a data-bind=\"click: koTestSurveyWidth.bind($data, \'1200px\')\" href=\"#\">1200px<\/a>";
html_main += "					<\/li>";
html_main += "					<li>";
html_main += "						<a data-bind=\"click: koTestSurveyWidth.bind($data, \'1000px\')\" href=\"#\">1000px<\/a>";
html_main += "					<\/li>";
html_main += "					<li>";
html_main += "						<a data-bind=\"click: koTestSurveyWidth.bind($data, \'800px\')\" href=\"#\">800px<\/a>";
html_main += "					<\/li>";
html_main += "					<li>";
html_main += "						<a data-bind=\"click: koTestSurveyWidth.bind($data, \'600px\')\" href=\"#\">600px<\/a>";
html_main += "					<\/li>";
html_main += "					<li>";
html_main += "						<a data-bind=\"click: koTestSurveyWidth.bind($data, \'400px\')\" href=\"#\">400px<\/a>";
html_main += "					<\/li>";
html_main += "				<\/ul>";
html_main += "			<\/div>";
html_main += "		<\/li>";
html_main += "		<li class=\"svd_actions\"><button class=\"btn btn-primary svd_save_btn\" data-bind=\"click: saveButtonClick, visible: koShowSaveButton\" type=\"button\"><span data-bind=\"text: $root.getLocString(\'ed.saveSurvey\')\"><\/span><\/button><\/li>";
html_main += "	<\/ul>";
html_main += "	<div class=\"panel svd_content\">";
html_main += "		<div class=\"row svd_survey_designer\" data-bind=\"visible: koViewType() == \'designer\'\">";
html_main += "			<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12 panel panel-default svd_toolbox\">";
html_main += "				<div class=\"btn-group-vertical\" style=\"width:100%;padding-right:2px\">";
html_main += "					<!-- ko foreach: questionTypes -->";
html_main += "					<div class=\"btn btn-default\" data-bind=\"click: $parent.clickQuestion, event:{dragstart: function(el, e) { $parent.draggingQuestion($data, e); return true;}, dragend: function(el, e) { $parent.dragEnd(); }}\" draggable=\"true\" style=\"text-align:center; margin:1px;width:100%\">";
html_main += "						<span data-bind=\"css: \'icon-\' + $data\"><\/span> <span class=\"svd_toolbox_item_text\" data-bind=\"text: $root.getLocString(\'qt.\' + $data)\"><\/span>";
html_main += "					<\/div><!-- \/ko  -->";
html_main += "					<!-- ko foreach: koCopiedQuestions -->";
html_main += "					<div class=\"btn btn-default\" data-bind=\"click: $parent.clickCopiedQuestion, event:{dragstart: function(el, e) { $parent.draggingCopiedQuestion($data, e); return true;}, dragend: function(el, e) { $parent.dragEnd(); }}\" draggable=\"true\" style=\"text-align:left; margin:1px;width:100%\">";
html_main += "						<span class=\"icon-default\"><\/span> <span class=\"svd_toolbox_item_text\" data-bind=\"text:name\"><\/span>";
html_main += "					<\/div><!-- \/ko  -->";
html_main += "				<\/div>";
html_main += "			<\/div>";
html_main += "				<div class=\"panel-heading input-group\">";
html_main += "					<div class=\"custom-select\">";
html_main += "						<select class=\"form-control\" data-bind=\"options: koObjects, optionsText: \'text\', value: koSelectedObject\">";
html_main += "						<\/select>";
html_main += "					<\/div>";
html_main += "					<div class=\"input-group-btn\">";
html_main += "						<button class=\"btn btn-default\" data-bind=\"enable: koCanDeleteObject, click: deleteCurrentObject, attr: { title: $root.getLocString(\'ed.delSelObject\')}\" type=\"button\"><span class=\"glyphicon glyphicon-remove\"><\/span><\/button>";
html_main += "					<\/div>";
html_main += "				<\/div>";
html_main += "			<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12 svd_editors\" style=\"padding-bottom:2em\">";
html_main += "				<div class=\"svd_pages_editor\" data-bind=\"template: { name: \'pageeditor\', data: pagesEditor }\"><\/div>";
html_main += "				<div class=\"svd_questions_editor\" id=\"scrollableDiv\">";
html_main += "					<div id=\"surveyjs\"><\/div>";
html_main += "				<\/div>";
html_main += "			<\/div>";
html_main += "			<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12 panel panel-default svd_properties\" >";
// html_main += "				<div class=\"panel-heading input-group\">";
// html_main += "					<div class=\"custom-select\">";
// html_main += "						<select class=\"form-control\" data-bind=\"options: koObjects, optionsText: \'text\', value: koSelectedObject\">";
// html_main += "						<\/select>";
// html_main += "					<\/div>";
// html_main += "					<div class=\"input-group-btn\">";
// html_main += "						<button class=\"btn btn-default\" data-bind=\"enable: koCanDeleteObject, click: deleteCurrentObject, attr: { title: $root.getLocString(\'ed.delSelObject\')}\" type=\"button\"><span class=\"glyphicon glyphicon-remove\"><\/span><\/button>";
// html_main += "					<\/div>";
// html_main += "				<\/div>";
html_main += "				<div data-bind=\"template: { name: \'objecteditor\', data: selectedObjectEditor }\"><\/div>";
html_main += "				<div class=\"panel-footer\" data-bind=\"visible:surveyVerbs.koHasVerbs\">";
html_main += "					<div data-bind=\"template: { name: \'objectverbs\', data: surveyVerbs }\"><\/div>";
html_main += "				<\/div>";
html_main += "			<\/div>";
html_main += "		<\/div>";
html_main += "		<div class=\"svd_json_editor\" data-bind=\"visible: koViewType() == \'editor\'\" id=\"surveyjsJSONEditor\"><\/div>";
html_main += "		<div data-bind=\"visible: koViewType() == \'test\', style: {width: koTestSurveyWidth}\" id=\"surveyjsTest\">";
html_main += "			<div id=\"surveyjsExample\"><\/div>";
html_main += "			<div id=\"surveyjsExampleResults\"><\/div><button data-bind=\"click:selectTestClick, text: $root.getLocString(\'ed.testSurveyAgain\')\" id=\"surveyjsExamplereRun\" style=\"display:none\">Test Again<\/button>";
html_main += "		<\/div>";
html_main += "		<div data-bind=\"visible: koViewType() == \'embed\'\" id=\"surveyjsEmbed\">";
html_main += "			<div data-bind=\"template: { name: \'surveyembeding\', data: surveyEmbeding }\"><\/div>";
html_main += "		<\/div>";
html_main += "	<\/div>";
html_main += "<\/div>";
// javascript section //
html_main += '<script type="text/html" id="objecteditor">    <table class="table svd_table-nowrap">        <tbody data-bind="foreach: koProperties">            <tr data-bind="click: $parent.changeActiveProperty($data), css: {\'active\': $parent.koActiveProperty() == $data}">                <td data-bind="text: displayName, attr: {title: title}" width="50%"></td>                <td width="50%">                    <span data-bind="text: koText, visible: $parent.koActiveProperty() != $data && (koText() || $data.editorType == \'boolean\'), attr: {title: koText}" style="text-overflow:ellipsis;white-space:nowrap;overflow:hidden"></span>                    <div data-bind="visible: $parent.koActiveProperty() == $data || (!koText() && $data.editorType != \'boolean\')">                        <!-- ko template: { name: \'propertyeditor-\' + editorType, data: $data } -->                        <!-- /ko -->                    </div>                </td>            </tr>        </tbody>    </table></script><script type="text/html" id="objectverbs">    <!-- ko foreach: koVerbs -->        <!-- /ko  --></script><script type="text/html" id="pageeditor">    <ul class="nav nav-tabs" data-bind="tabs:true">        <!-- ko foreach: koPages -->        <li data-bind="css: {active: koSelected()},event:{           keydown:function(el, e){ $parent.keyDown(el, e); },           dragstart:function(el, e){ $parent.dragStart(el); return true; },           dragover:function(el, e){ $parent.dragOver(el);},           dragend:function(el, e){ $parent.dragEnd();},           drop:function(el, e){ $parent.dragDrop(el);}         }">             <a class="svd_page_nav" href="#" data-bind="click:$parent.selectPageClick">                <span data-bind="text: title"></span>            </a>        </li>        <!-- /ko  -->        <li><button class="btn btn-default svd_add_new_page_btn" data-bind="click:addNewPageClick"><span class="glyphicon glyphicon-plus"></span></button></li>    </ul></script><script type="text/html" id="surveyembeding">    <div class="row">        <select data-bind="value:koLibraryVersion">            <option value="knockout" data-bind="text: $root.getLocString(\'ew.knockout\')"></option>            <option value="react" data-bind="text: $root.getLocString(\'ew.react\')"></option>        </select>        <select data-bind="value:koScriptUsing">            <option value="bootstrap" data-bind="text: $root.getLocString(\'ew.bootstrap\')"></option>            <option value="standard" data-bind="text: $root.getLocString(\'ew.standard\')"></option>        </select>        <select data-bind="value:koShowAsWindow">            <option value="page" data-bind="text: $root.getLocString(\'ew.showOnPage\')"></option>            <option value="window" data-bind="text: $root.getLocString(\'ew.showInWindow\')"></option>        </select>        <label class="checkbox-inline" data-bind="visible:koHasIds">            <input type="checkbox" data-bind="checked:koLoadSurvey" />            <span data-bind="text: $root.getLocString(\'ew.loadFromServer\')"></span>        </label>    </div>    <div class="panel">        <div class="panel-heading" data-bind="text: $root.getLocString(\'ew.titleScript\')"></div>        <div id="surveyEmbedingHead" style="height:70px;width:100%"></div>    </div>    <div class="panel" data-bind="visible: koVisibleHtml">        <div class="panel-heading"  data-bind="text: $root.getLocString(\'ew.titleHtml\')"></div>        <div id="surveyEmbedingBody" style="height:30px;width:100%"></div>    </div>    <div class="panel">        <div class="panel-heading"  data-bind="text: $root.getLocString(\'ew.titleJavaScript\')"></div>        <div id="surveyEmbedingJava" style="height:300px;width:100%"></div>    </div></script><script type="text/html" id="propertyeditor-boolean">    <input class="form-control" type="checkbox" data-bind="checked: koValue" /></script><script type="text/html" id="propertyeditor-dropdown">    <div class="custom-select">        <select class="form-control" data-bind="value: koValue, options: choices"  style="width:100%"></select>    </div></script><script type="text/html" id="propertyeditor-html">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-html">    <textarea id="TxtAreaContent" class="form-control" data-bind="value:koValue" style="width:100%" rows="10" autofocus="autofocus"></textarea></script><script type="text/html" id="propertyeditor-itemvalues">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-itemvalues">    <div style="overflow-y: auto; overflow-x:hidden; max-height:400px">        <table class="table">            <thead>                <tr>                    <th></th>                    <th data-bind="text: $root.getLocString(\'pe.value\')"></th>                    <th data-bind="text: $root.getLocString(\'pe.text\')"></th>                    <th></th>                </tr>            </thead>            <tbody>                <!-- ko foreach: koItems -->                <tr>                    <td>                        <div class="btn-group" role="group">                            <button type="button" class="btn btn-xs" data-bind="visible: $index() > 0, click: $parent.onMoveUpClick"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></button>                            <button type="button" class="btn btn-xs" style="float:none" data-bind="visible: $index() < $parent.koItems().length - 1, click: $parent.onMoveDownClick"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span></button>                        </div>                    </td>                    <td>                        <input type="text" class="form-control" data-bind="value:koValue" style="width:200px" />                        <div class="alert alert-danger no-padding" role="alert" data-bind="visible:koHasError, text: $root.getLocString(\'pe.enterNewValue\')"></div>                    </td>                    <td><input type="text" class="form-control" data-bind="value:koText" style="width:200px" /></td>                    <td><button type="button" class="btn btn-xs" data-bind="click: $parent.onDeleteClick"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button></td>                </tr>                <!-- /ko -->            </tbody>        </table>    </div>    <div class="row btn-toolbar">        <input type="button" class="btn btn-success" data-bind="click: onAddClick, value: $root.getLocString(\'pe.addNew\')" />        <input type="button" class="btn btn-danger" data-bind="click: onClearClick, value: $root.getLocString(\'pe.removeAll\')" />    </div></script><script type="text/html" id="propertyeditor-matrixdropdowncolumns">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-matrixdropdowncolumns">    <table class="table">        <thead>            <tr>                <th data-bind="text: $root.getLocString(\'pe.required\')"></th>                <th data-bind="text: $root.getLocString(\'pe.cellType\')"></th>                <th data-bind="text: $root.getLocString(\'pe.name\')"></th>                <th data-bind="text: $root.getLocString(\'pe.title\')"></th>                <th></th>            </tr>        </thead>        <tbody>            <!-- ko foreach: koItems -->            <tr>                <td>                    <a href="#" data-bind="visible:koHasChoices, click: onShowChoicesClick">                        <span class="glyphicon" data-bind="css: {\'glyphicon-chevron-down\': !koShowChoices(), \'glyphicon-chevron-up\': koShowChoices()}"></span>                    </a>                    <input type="checkbox" data-bind="checked: koIsRequired" />                </td>                <td>                    <select class="form-control" data-bind="options: cellTypeChoices, value: koCellType"  style="width:110px"></select>                </td>                <td>                    <input type="text" class="form-control" data-bind="value:koName" style="width:100px" />                    <div class="alert alert-danger no-padding" role="alert" data-bind="visible:koHasError, text: $root.getLocString(\'pe.enterNewValue\')"></div>                </td>                <td><input type="text" class="form-control" data-bind="value:koTitle" style="width:120px" /></td>                <td><input type="button" class="btn" data-bind="click: $parent.onDeleteClick, value: $root.getLocString(\'pe.delete\')"/></td>            </tr>            <tr data-bind="visible: koShowChoices() && koHasChoices()">                <td colspan="4" style="border-top-style:none">                    <div class="form-group">                        <label class="control-label col-sm-3" data-bind="text:$root.getLocString(\'pe.hasOther\')"></label>                        <div class="col-sm-2">                            <input type="checkbox" data-bind="checked: koHasOther" />                        </div>                        <div class="col-sm-7" data-bind="visible: !koHasColCount()"></div>                        <label class="control-label col-sm-3" data-bind="visible:koHasColCount, text:$root.getLocString(\'pe.colCount\')"></label>                        <select class="form-control col-sm-4" data-bind="visible:koHasColCount, options: colCountChoices, value: koColCount" style="width:110px"></select>                    </div>                    <div class="modal-body svd_notopbottompaddings">                        <!-- ko template: { name: \'propertyeditorcontent-itemvalues\', data: choicesEditor } -->                        <!-- /ko -->                    </div>                </td>            </tr>            <!-- /ko -->            <tr>                <td colspan="3">                    <div class="row btn-toolbar">                        <input type="button" class="btn btn-success" data-bind="click: onAddClick, value: $root.getLocString(\'pe.addNew\')"/>                        <input type="button" class="btn btn-danger" data-bind="click: onClearClick, value: $root.getLocString(\'pe.removeAll\')"" />                    </div>                </td>            </tr>        </tbody>    </table></script><script type="text/html" id="propertyeditor-modal">    <div class="input-group" data-bind="visible:!editor.isEditable">        <span data-bind="text: koText"></span>        <div class="input-group-btn">            <button type="button"  class="btn btn-default"data-toggle="modal" style="padding: 2px;" data-bind="attr: {\'data-target\' : modalNameTarget}">                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>            </button>        </div>    </div>    <div class="input-group" data-bind="visible:editor.isEditable" style="display:table">        <input class="form-control" type="text" data-bind="value: koValue" style="display:table-cell; width:100%" />        <div class="input-group-btn">            <button type="button" class="btn btn-default" style="display:table-cell; padding: 2px;"  data-toggle="modal" data-bind="attr: {\'data-target\' : modalNameTarget}">                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>            </button>        </div>    </div>    <div data-bind="attr: {id : modalName}" class="modal fade" role="dialog">        <div class="modal-dialog">            <div class="modal-content">                <div class="modal-header">                    <button type="button" class="close" data-dismiss="modal">&times;</button>                    <h4 class="modal-title" data-bind="text:editor.title"></h4>                </div>                  <div class="modal-body svd_notopbottompaddings">                    <!-- ko template: { name: \'propertyeditorcontent-\' + editorType, data: editor } -->                    <!-- /ko -->                </div>                <div class="modal-footer">    <input type="button" class="btn btn-primary" data-bind="click: editor.onUploadClick, value: $root.getLocString(\'pe.upload\')" style="width:100px" />                <input type="button" class="btn btn-success" data-bind="click: editor.onApplyClick, value: $root.getLocString(\'pe.apply\')" style="width:100px" />                    <input type="button" class="btn btn-default" data-bind="click: editor.onResetClick, value: $root.getLocString(\'pe.reset\')" style="width:100px" />                    <input type="button" class="btn btn-default" data-dismiss="modal" data-bind="value: $root.getLocString(\'pe.close\')" style="width:100px" />                </div>            </div>        </div>    </div></script><script type="text/html" id="propertyeditor-number">    <input class="form-control" type="number" data-bind="value: koValue" style="width:100%" /></script><script type="text/html" id="propertyeditor-restfull">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-restfull">    <form>        <div class="form-group">            <label for="url">Url:</label>            <input id="url" type="text" data-bind="value:koUrl" class="form-control" />        </div>        <div class="form-group">            <label for="path">Path:</label>            <input id="path" type="text" data-bind="value:koPath" class="form-control" />        </div>        <div class="form-group">            <label for="valueName">valueName:</label>            <input id="valueName" type="text" data-bind="value:koValueName" class="form-control" />        </div>        <div class="form-group">            <label for="titleName">titleName:</label>            <input id="titleName" type="text" data-bind="value:koTitleName" class="form-control" />        </div>    </form>    <div id="restfullSurvey" style="width:100%;height:150px"></div></script><script type="text/html" id="propertyeditor-string">    <input class="form-control" type="text" data-bind="value: koValue" style="width:100%" /></script><script type="text/html" id="propertyeditor-text">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-text">    <textarea class="form-control" data-bind="value:koValue" style="width:100%" rows="10" autofocus="autofocus"></textarea></script><script type="text/html" id="propertyeditor-textitems">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-textitems"><div class="panel">    <table class="table">        <thead>            <tr>                <th data-bind="text: $root.getLocString(\'pe.name\')"></th>                <th data-bind="text: $root.getLocString(\'pe.title\')"></th>                <th></th>            </tr>        </thead>        <tbody>            <!-- ko foreach: koItems -->            <tr>                <td><input type="text" class="form-control" data-bind="value:koName" style="width:200px" /></td>                <td><input type="text" class="form-control" data-bind="value:koTitle" style="width:200px" /></td>                <td><input type="button" class="btn" data-bind="click: $parent.onDeleteClick, value: $root.getLocString(\'pe.delete\')"/></td>            </tr>            <!-- /ko -->            <tr>                <td colspan="4"><input type="button" class="btn btn-success" data-bind="click: onAddClick, value: $root.getLocString(\'pe.addNew\')"/></td>            </tr>        </tbody>    </table></div></script><script type="text/html" id="propertyeditor-triggers">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-triggers"><div class="panel">    <div class="panel-heading">        <div class="row input-group">            <button type="button" class="dropdown-toggle input-group-addon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">                <span class="glyphicon glyphicon-plus"></span>            </button>            <ul class="dropdown-menu input-group">                <!-- ko foreach: availableTriggers -->                <li><a href="#" data-bind="click: $parent.onAddClick($data)"><span data-bind="text:$data"></span></a></li>                <!-- /ko  -->            </ul>            <select class="form-control" data-bind="options: koItems, optionsText: \'koText\', value: koSelected"></select>            <span class="input-group-btn">                <button type="button" data-bind="enable: koSelected() != null, click: onDeleteClick" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>            </span>        </div>    </div>    <div data-bind="visible: koSelected() == null">        <div data-bind="visible: koQuestions().length == 0, text: $root.getLocString(\'pe.noquestions\')"></div>        <div data-bind="visible: koQuestions().length > 0, text: $root.getLocString(\'pe.createtrigger\')"></div>    </div>    <div data-bind="visible: koSelected() != null">        <div data-bind="with: koSelected">            <div class="row form-inline">                <div class="col-sm-4">                    <span data-bind="text: $root.getLocString(\'pe.triggerOn\')"></span><select class="form-control" data-bind="options:$parent.koQuestions, value: koName"></select> <span> </span>                </div>                <div class="col-sm-4">                    <select class="form-control" data-bind="options:availableOperators, optionsValue: \'name\', optionsText: \'text\', value:koOperator"></select>                </div>                <div class="col-sm-4">                    <input class="form-control" style="padding: 0" type="text" data-bind="visible: koRequireValue, value:koValue" />                </div>            </div>            <!-- ko if: koType() == \'visibletrigger\' -->            <div class="row">                <div class="col-sm-6">                    <!-- ko template: { name: \'propertyeditor-triggersitems\', data: pages } -->                    <!-- /ko -->                </div>                <div class="col-sm-6">                    <!-- ko template: { name: \'propertyeditor-triggersitems\', data: questions } -->                    <!-- /ko -->                </div>            </div>            <!-- /ko -->            <!-- ko if: koType() == \'completetrigger\' -->            <div class="row">               <div style="margin: 10px" data-bind="text: $root.getLocString(\'pe.triggerCompleteText\')"></div>            </div>            <!-- /ko -->            <!-- ko if: koType() == \'setvaluetrigger\' -->            <div class="row form-inline" style="margin-top:10px">                <div class="col-sm-6">                    <span data-bind="text: $root.getLocString(\'pe.triggerSetToName\')"></span><input class="form-control" type="text" data-bind="value:kosetToName" />                </div>                <div class="col-sm-1">                </div>                <div class="col-sm-5">                    <span data-bind="text: $root.getLocString(\'pe.triggerSetValue\')"></span><input class="form-control" type="text" data-bind="value:kosetValue" />                </div>            </div>            <div class="row form-inline">                <div class="col-sm-12">                    <input type="checkbox" data-bind="checked: koisVariable" /> <span data-bind="text: $root.getLocString(\'pe.triggerIsVariable\')"></span>                </div>            </div>            <!-- /ko -->        </div>    </div></div></script><script type="text/html" id="propertyeditor-triggersitems">    <div class="panel no-margins no-padding">        <div class="panel-heading">            <span data-bind="text: title"></span>        </div>        <div class="input-group">            <select class="form-control" multiple="multiple" data-bind="options:koChoosen, value: koChoosenSelected"></select>            <span class="input-group-btn" style="vertical-align:top">                <button type="button" data-bind="enable: koChoosenSelected() != null, click: onDeleteClick" class="btn"><span class="glyphicon glyphicon-remove"></span></button>            </span>        </div>        <div class="input-group" style="margin-top:5px">            <select class="form-control" data-bind="options:koObjects, value: koSelected"></select>            <span class="input-group-btn">                <button type="button" data-bind="enable: koSelected() != null, click: onAddClick" style="width:40px" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span></button>            </span>        </div>    </div></script><script type="text/html" id="propertyeditor-validators">    <!-- ko template: { name: \'propertyeditor-modal\', data: $data } --><!-- /ko --></script><script type="text/html" id="propertyeditorcontent-validators"><div class="panel">    <div class="panel-heading">        <div class="row input-group">            <button type="button" class="dropdown-toggle input-group-addon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">                <span class="glyphicon glyphicon-plus"></span>            </button>            <ul class="dropdown-menu input-group">                <!-- ko foreach: availableValidators -->                <li><a href="#" data-bind="click: $parent.onAddClick($data)"><span data-bind="text:$data"></span></a></li>                <!-- /ko  -->            </ul>            <select class="form-control" data-bind="options: koItems, optionsText: \'text\', value: koSelected"></select>            <span class="input-group-btn">                <button type="button" data-bind="enable: koSelected() != null, click: onDeleteClick" class="btn"><span class="glyphicon glyphicon-remove"></span></button>            </span>        </div>    </div>    <div data-bind="template: { name: \'objecteditor\', data: selectedObjectEditor }"></div></div></script>';

// Designer Section //

var html_design = "";
html_design += "<div data-bind=\"event:{ dragenter:function(el, e){ dragEnter(e);}, dragleave:function(el, e){ dragLeave(e);}, dragover:function(el, e){ return false;}, drop:function(el, e){ dragDrop(e);}}\">";
html_design += "	<h4 data-bind=\"visible: (title.length &gt; 0) && data.showPageTitles, text: koNo() + processedTitle, css: $root.css.pageTitle\"><\/h4><!-- ko foreach: { data: rows, as: \'row\'} -->";
// html_design += "<div class=\"itemCount\">";
html_design += "	<div class=\"svd_question_container\" data-bind=\"visible: row.koVisible, css: $root.css.row\">";
html_design += "		<!-- ko foreach: { data: row.questions, as: \'question\' , afterRender: row.koAfterRender } -->";
html_design += "<div class=\"itemCount\"></div>";
html_design += "		<div data-bind=\"visible: question.koIsDragging\">";
html_design += "			<!-- ko template: { if: $root.koDraggingSource(), name: \'survey-question\', data: $root.koDraggingSource(), as: \'question\', templateOptions: { isDragging: true } } --><!-- \/ko -->";
html_design += "		<\/div><!-- ko template: { name: \'survey-question\', data: question, templateOptions: { isDragging: false } } --><!-- \/ko --><!-- \/ko -->";
html_design += "	<\/div><!-- \/ko -->";
html_design += "	<div class=\"well\" data-bind=\"visible:$root.isDesignMode && questions.length == 0\">";
html_design += "		<span data-bind=\"visible: !koDraggingBottom(), text:$root.getEditorLocString(\'survey.dropQuestion\')\"><\/span>";
html_design += "		<div data-bind=\"visible: koDraggingBottom\">";
html_design += "			<!-- ko template: { if: $root.koDraggingSource(), name: \'survey-question\', data: $root.koDraggingSource(), as: \'question\', templateOptions: { isDragging: true } } --><!-- \/ko -->";
html_design += "		<\/div>";
html_design += "	<\/div>";
html_design += "	<div data-bind=\"visible: questions.length &gt; 0 && koDraggingBottom()\">";
html_design += "		<!-- ko template: { if: $root.koDraggingSource(), name: \'survey-question\', data: $root.koDraggingSource(), as: \'question\', templateOptions: { isDragging: true } } --><!-- \/ko -->";
html_design += "	<\/div>";
// html_design += "</div>";
html_design += "<\/div>";

// Header Section

var html_header = "";
html_header += "<div class=\"svd_question\" data-bind=\"style: {display: question.koVisible()|| $root.isDesignMode ? \'inline-block\': \'none\', marginLeft: question.koMarginLeft, paddingRight: question.koPaddingRight, width: question.koRenderWidth }, attr : {id: id, draggable: $root.isDesignMode}, click: $root.isDesignMode ? koOnClick: null, event:{ dragstart:function(el, e){ dragStart(e); return true; }, dragover:function(el, e){ if(!question.isDragging) dragOver(e);}, dragend:function(el, e){ dragEnd(e);}, drop:function(el, e){ dragDrop(e);} }, css:{svd_q_design_border: $root.isDesignMode, svd_q_selected : koIsSelected, \'well well-sm\': $root.isDesignMode}\" style=\"vertical-align:top\">";
html_header += "	<div data-bind=\"css:{svd_q_design: $root.isDesignMode}, style:{opacity: question.koIsDraggingSource() ? 0.4 : 1}\">";
html_header += "		<div class=\"alert alert-danger\" data-bind=\"visible: koErrors().length &gt; 0, foreach: koErrors\" role=\"alert\">";
html_header += "			<div>";
html_header += "				<span aria-hidden=\"true\" class=\"glyphicon glyphicon-exclamation-sign\"><\/span> <span data-bind=\"text:$data.getText()\"><\/span>";
html_header += "			<\/div>";
html_header += "		<\/div><!-- ko if: question.hasTitle -->";
html_header += "<div data-bind=\"html: question.images\"></div>";
html_header += "		<h5 data-bind=\"visible: $root.questionTitleLocation == \'top\', text: question.koTitle(), css: $root.css.question.title\"><\/h5><!-- \/ko --><!-- ko template: { name: \'survey-question-\' + question.getType(), data: question } --><!-- \/ko -->";
html_header += "		<div data-bind=\"visible: question.hasComment\">";
html_header += "			<div data-bind=\"text:question.commentText\"><\/div>";
html_header += "			<div data-bind=\"template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': true } }\"><\/div>";
html_header += "		<\/div><!-- ko if: question.hasTitle -->";
html_header += "		<h5 data-bind=\"visible: $root.questionTitleLocation == \'bottom\', text: question.koTitle(), css: $root.css.question.title\"><\/h5><!-- \/ko -->";
html_header += "	<\/div>";
// html_header += "	<div class=\"svd_question_menu\" data-bind=\"visible: koIsSelected\">";
// html_header += "		<button aria-expanded=\"false\" aria-haspopup=\"true\" class=\"btn btn-primary btn-xs dropdown-toggle\" data-toggle=\"dropdown\" type=\"button\"><span class=\"glyphicon glyphicon-option-horizontal\"><\/span><\/button>";
// html_header += "		<ul class=\"dropdown-menu\">";
// html_header += "			<li><button class=\"btn btn-primary btn-xs\" data-bind=\"click: $root.copyQuestionClick, text:$root.getEditorLocString(\'survey.addToToolbox\')\"><\/button><\/li>";
// html_header += "			<li><button class=\"btn btn-primary btn-xs\" data-bind=\"click: $root.fastCopyQuestionClick, text:$root.getEditorLocString(\'survey.copy\')\"><\/button><\/li>";
// html_header += "		<\/ul>";
// html_header += "	<\/div>";
html_header += "<\/div>";

// Suyvey template

var template = "";
template += "<script id=\"survey-comment\" type=\"text\/html\">";
template += "  <input data-bind=\"value:$data.question.koComment, visible:$data.visible, css: $root.css.question.comment\" \/>";
template += "<\/script>";
template += "<div data-bind=\"css: $root.css.root\">";
template += "	<div data-bind=\"visible: (title.length &gt; 0) && showTitle && koState() != \'completed\', css: $root.css.header\">";
template += "		<h1 data-bind=\"html:title\"><\/h1>";
template += "		<h4 data-bind=\"html:description\"><\/h4>";
template += "	<\/div><!-- ko if: koState() == \"running\" -->";
template += "	<div data-bind=\"css: $root.css.body\">";
template += "		<div data-bind=\"visible: showProgressBar ==\'top\', template: { name: \'survey-progress\', data: $data }\"><\/div>";
template += "		<div data-bind=\"template: { name: \'survey-page\', data: koCurrentPage }\" id=\"sq_page\"><\/div>";
template += "		<div data-bind=\"visible: showProgressBar ==\'bottom\', template: { name: \'survey-progress\', data: $data }\" style=\"margin-top:10px\"><\/div>";
template += "	<\/div>";
template += "	<div data-bind=\"visible: showNavigationButtons && !isDesignMode, css: $root.css.footer\">";
template += "		<input data-bind=\"value: pagePrevText, click: prevPage, visible: !koIsFirstPage(), css: $root.cssNavigationPrev\" type=\"button\"> <input data-bind=\"value: pageNextText, click: nextPage, visible: !koIsLastPage(), css: $root.cssNavigationNext\" type=\"button\"> <input data-bind=\"value: completeText, click: completeLastPage, visible: koIsLastPage(), css: $root.cssNavigationComplete\" type=\"button\">";
template += "	<\/div><!-- \/ko --><!-- ko if: koState() == \"completed\" -->";
template += "	<div data-bind=\"html: processedCompletedHtml\"><\/div><!-- \/ko --><!-- ko if: koState() == \"loading\" -->";
template += "	<div data-bind=\"html: processedLoadingHtml\"><\/div><!-- \/ko --><!-- ko if: koState() == \"empty\" -->";
template += "	<div data-bind=\"text:emptySurveyText, css: $root.css.body\"><\/div><!-- \/ko -->";
template += "<\/div>";
template += "<script id=\"survey-page\" type=\"text\/html\">";
template += "    <h4 data-bind=\"visible: (title.length > 0) && data.showPageTitles, text: koNo() + processedTitle, css: $root.css.pageTitle\"><\/h4>    <!-- ko foreach: { data: rows, as: \'row\'} -->    <div data-bind=\"visible: row.koVisible, css: $root.css.row\">        <!-- ko foreach: { data: row.questions, as: \'question\' , afterRender: row.koAfterRender } -->";
// template += "<div data-bind=\"html: question.images\"></div>";
template += "            <!-- ko template: { name: \'survey-question\', data: question } --><!-- \/ko -->        <!-- \/ko -->    <\/div>    <!-- \/ko -->";
// template += "<div data-bind=\"html: question.images\"></div>";
template += "<\/script>";
template += "<script id=\"survey-progress\" type=\"text\/html\">";
template += "    <div style=\"width:60%;\" data-bind=\"css: $root.css.progress\">        <div data-bind=\"css: $root.css.progressBar, style:{width: koProgress() + \'%\'}\"             role=\"progressbar\" aria-valuemin=\"0\"             aria-valuemax=\"100\">            <span data-bind=\"text:koProgressText\"><\/span>        <\/div>    <\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-checkbox\" type=\"text\/html\">";
// template += "<div data-bind=\"html: question.images\"></div>";
// template += "<div data-bind=\"html: question.images\"><\/div>";
template += "    <form data-bind=\"css: $root.css.checkbox.root\">";
template += "        <!-- ko foreach: { data: question.koVisibleChoices, as: \'item\', afterRender: question.koAfterRender}  -->        <div id=\"choices_items\" data-bind=\"style:{width: question.koWidth, \'margin-right\': question.colCount == 0 ? \'5px\': \'0px\'}, css: $root.css.checkbox.item\">";
template += "            <label data-bind=\"css: $root.css.checkbox.item\">                <input type=\"checkbox\" data-bind=\"attr: {name: question.name, value: item.value}, checked: question.koValue\" \/>                <span data-bind=\"text: item.text\"><\/span>            <\/label>            <div data-bind=\"visible: question.hasOther && ($index() == question.koVisibleChoices().length-1)\">                <div data-bind=\"template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }, css: $root.css.checkbox.other\"><\/div>            <\/div>        <\/div>        <!-- \/ko -->    <\/form>";
template += "<\/script>";
template += "<script id=\"survey-question-comment\" type=\"text\/html\">";
template += "    <textarea type=\"text\" data-bind=\"attr: {cols: question.cols, rows: question.rows}, value:question.koValue, css: $root.css.comment\" \/>";
template += "<\/script>";
template += "<script id=\"survey-question-dropdown\" type=\"text\/html\">";
template += "    <select data-bind=\"options: question.koVisibleChoices, optionsText: \'text\', optionsValue: \'value\', value: question.koValue, optionsCaption: question.optionsCaption, css: $root.css.dropdown\"><\/select>    <div data-bind=\"visible: question.hasOther\">        <div data-bind=\"template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }\"><\/div>    <\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-errors\" type=\"text\/html\">";
template += "    <div role=\"alert\" data-bind=\"visible: koErrors().length > 0, foreach: { data: koErrors, as: \'error\'}, css: $root.css.error.root\">        <div>            <span aria-hidden=\"true\" data-bind=\"css: $root.css.error.icon\"><\/span>            <span data-bind=\"text:error.getText(), css: $root.css.error.item\"><\/span>        <\/div>    <\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-file\" type=\"text\/html\">";
template += "    <input type=\"file\" data-bind=\"event: {change: dochange}\">    <div>        <img data-bind=\"attr: { src: question.koData, height: question.imageHeight, width: question.imageWidth }, visible: question.koHasValue\">    <\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-html\" type=\"text\/html\">";
template += "    <div data-bind=\"html: question.processedHtml\"><\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-matrix\" type=\"text\/html\">";
template += "    <table data-bind=\"css: $root.css.matrix.root\">        <thead>            <tr>                <th data-bind=\"visible: question.hasRows\"><\/th>                <!-- ko foreach: question.columns -->                <th data-bind=\"text:$data.text\"><\/th>                <!-- \/ko -->            <\/tr>        <\/thead>        <tbody>            <!-- ko foreach: { data: question.visibleRows, as: \'row\' } -->            <tr>                <td data-bind=\"visible: question.hasRows, text:row.text\"><\/td>                <!-- ko foreach: question.columns -->                <td>                    <input type=\"radio\" data-bind=\"attr: {name: row.fullName, value: $data.value}, checked: row.koValue\"\/>                <\/td>                <!-- \/ko -->            <\/tr>            <!-- \/ko -->        <\/tbody>    <\/table>";
template += "<\/script>";
template += "<script id=\"survey-question-matrixdropdown\" type=\"text\/html\">";
template += "    <div data-bind=\"style: {overflowX: question.horizontalScroll? \'scroll\': \'\'}\">        <table data-bind=\"css: $root.css.matrixdropdown.root\">            <thead>                <tr>                    <th><\/th>                    <!-- ko foreach: question.columns -->                    <th data-bind=\"text: question.getColumnTitle($data), style: { minWidth: question.getColumnWidth($data) }\"><\/th>                    <!-- \/ko -->                <\/tr>            <\/thead>            <tbody>                <!-- ko foreach: { data: question.visibleRows, as: \'row\' } -->                <tr>                    <td data-bind=\"text:row.text\"><\/td>                    <!-- ko foreach: row.cells-->                    <td>                        <!-- ko template: { name: \'survey-question-errors\', data: $data.question } -->                        <!-- \/ko -->                        <!-- ko template: { name: \'survey-question-\' + $data.question.getType(), data: $data.question, as: \'question\' } -->                        <!-- \/ko -->                    <\/td>                    <!-- \/ko -->                <\/tr>                <!-- \/ko -->            <\/tbody>        <\/table>    <\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-matrixdynamic\" type=\"text\/html\">";
template += "    <div data-bind=\"style: {overflowX: question.horizontalScroll? \'scroll\': \'\'}\">        <table data-bind=\"css: $root.css.matrixdynamic.root\">            <thead>                <tr>                    <!-- ko foreach: question.columns -->                    <th data-bind=\"text: question.getColumnTitle($data), style: { minWidth: question.getColumnWidth($data) }\"><\/th>                    <!-- \/ko -->                    <th><\/th>                <\/tr>            <\/thead>            <tbody>                <!-- ko foreach: { data: question.koRows, as: \'row\' } -->                <tr>                    <!-- ko foreach: row.cells-->                    <td>                        <!-- ko template: { name: \'survey-question-errors\', data: $data.question } -->                        <!-- \/ko -->                        <!-- ko template: { name: \'survey-question-\' + $data.question.getType(), data: $data.question, as: \'question\' } -->                        <!-- \/ko -->                    <\/td>                    <!-- \/ko -->                    <td><input type=\"button\" data-bind=\"click:question.koRemoveRowClick, css: $root.css.matrixdynamic.button, value: question.removeRowText\" \/><\/td>                <\/tr>                <!-- \/ko -->            <\/tbody>        <\/table>    <\/div>    <input type=\"button\" data-bind=\"click:question.koAddRowClick, css: $root.css.matrixdynamic.button, value: question.addRowText\" \/>";
template += "<\/script>";
template += "<script id=\"survey-question-multipletext\" type=\"text\/html\">";
template += "    <table data-bind=\"css: $root.css.multipletext.root, foreach: { data:  question.koRows, as: \'row\' }\">        <tr data-bind=\"foreach: { data: row, as: \'item\' }\">            <td data-bind=\"text: item.title, css: $root.css.multipletext.itemTitle\"><\/td>            <td><input type=\"text\" style=\"float:left\" data-bind=\"attr: {size: question.itemSize}, value: item.koValue, css: $root.css.multipletext.itemValue\" \/><\/td>        <\/tr>    <\/table>";
template += "<\/script>";
template += "<script id=\"survey-question-radiogroup\" type=\"text\/html\">";
template += "    <form data-bind=\"css: $root.css.radiogroup.root\">        <!-- ko foreach: { data: question.koVisibleChoices, as: \'item\', afterRender: question.koAfterRender}  -->        <div  data-bind=\"style:{width: question.koWidth, \'margin-right\': question.colCount == 0 ? \'5px\': \'0px\'}, css: $root.css.radiogroup.item\">            <label data-bind=\"css: $root.css.radiogroup.item\">                <input type=\"radio\" data-bind=\"attr: {name: question.name, value: item.value}, checked: question.koValue\" \/>                <span data-bind=\"text: item.text\"><\/span>            <\/label>            <div data-bind=\"visible: question.hasOther && ($index() == question.koVisibleChoices().length-1)\">                <div data-bind=\"template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible}}, css: $root.css.radiogroup.other\"><\/div>            <\/div>        <\/div>        <!-- \/ko -->    <\/form>";
template += "<\/script>";
template += "<script id=\"survey-question-rating\" type=\"text\/html\">";
template += "    <div data-bind=\"css: $root.css.rating.root\">        <!-- ko foreach: question.koVisibleRateValues -->        <label data-bind=\"css: question.koGetCss($data)\">            <input type=\"radio\" style=\"display: none;\"                    data-bind=\"attr: {name: question.name, id: question.name + $index(), value: $data.value}, event: { change: question.koChange}\" \/>            <span data-bind=\"visible: $index() == 0, text: question.mininumRateDescription\"><\/span>            <span data-bind=\"text: $data.text\"><\/span>            <span data-bind=\"visible: $index() == (question.koVisibleRateValues().length-1), text: question.maximumRateDescription\"><\/span>        <\/label>        <!-- \/ko -->    <\/div>    <div data-bind=\"visible: question.hasOther\">        <div data-bind=\"template: { name: \'survey-comment\', data: {\'question\': question } }\"><\/div>    <\/div>";
template += "<\/script>";
template += "<script id=\"survey-question-text\" type=\"text\/html\">";
template += "    <input data-bind=\"attr: {type: question.inputType, size: question.size}, value:question.koValue, css: $root.css.text\"\/>";
template += "<\/script>";
template += "<script id=\"survey-question\" type=\"text\/html\">";
template += "    <div style=\"vertical-align:top\" data-bind=\"css: $root.css.question.root, style: {display: question.koVisible() ? \'inline-block\': \'none\', marginLeft: question.koMarginLeft, paddingRight: question.koPaddingRight, width: question.koRenderWidth }, attr: {id: id}\">        <!-- ko if: question.hasTitle -->        <h5 data-bind=\"visible: $root.questionTitleLocation == \'top\', text: question.koTitle(), css: $root.css.question.title\"><\/h5>        <!-- \/ko -->        <!-- ko template: { name: \'survey-question-errors\', data: question } -->        <!-- \/ko -->        <!-- ko template: { name: \'survey-question-\' + question.getType(), data: question, afterRender: question.koQuestionAfterRender } -->        <!-- \/ko -->        <div data-bind=\"visible: question.hasComment\">            <div data-bind=\"text:question.commentText\"><\/div>            <div data-bind=\"template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': true } }\"><\/div>        <\/div>        <!-- ko if: question.hasTitle -->        <h5 data-bind=\"visible: $root.questionTitleLocation == \'bottom\', text: question.koTitle(), css: $root.css.question.title\"><\/h5>        <!-- \/ko -->    <\/div>";
template += "<\/script>";